weights: /content/drive/MyDrive/object-detection-checkpoints/pretrained_optimized/PWMFD_yolov5s_mosaic_frozen10_sgd_ep50_lr01_trainres320_run/weights/last.pt
cfg: ''
data: /content/config/PWMFD_yolov5.yaml
hyp: hyp.yaml
epochs: 50
batch_size: 32
imgsz: 320
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: /content/drive/MyDrive/object-detection-checkpoints/pretrained_optimized
name: PWMFD_yolov5s_mosaic_frozen10_sgd_ep50_lr01_trainres320_run
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 10
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /content/drive/MyDrive/object-detection-checkpoints/pretrained_optimized/PWMFD_yolov5s_mosaic_frozen10_sgd_ep50_lr01_trainres320_run
